import { RegistroPaciente } from '@/types/paciente';

export const MOCK_PACIENTES: RegistroPaciente[] = [
  {
    numero: 1,
    duplaACargo: 'Dupla 1 (Ps. Tomás Valenzuela - T.O. Camila Soto)',
    estado: 'En Seguimiento',
    fechaDerivacionDupla: '2026-03-02',
    fechaEgreso: '',
    fechaMaximaContactoInicial: '2026-03-05',
    fechaIngresoUego: '2026-03-01',
    observacionesIngreso: 'Ingreso derivado desde urgencias pediátricas. Familia receptiva.',
    nombre: 'Valentina Isidora Paz Gómez',
    rut: '22.456.789-3',
    edad: 14,
    eg: 'N/A',
    tipologia: 'Salud Mental Infanto-Juvenil',
    diagnostico: 'Trastorno de Ansiedad Generalizada con somatización',
    observacionesDiagnostico: 'Sintomatología ansiosa moderada ante exigencia escolar.',
    ingresoHorarioEspecial: 'Fin de semana',
    telefono: '+56 9 8765 4321',
    observacionesContacto: 'Madre atiende preferentemente en las tardes.',
    migrante: 'No',
    puebloOriginario: 'No',
    entregaRecuerdo: 'Sí',
    entregaDiptico: 'Sí',
    acompanamientoAtencionCerrada: 'Sí',
    controlAmbulatorioPsicosocial: 'Sí',
    atencion1: '2026-03-04 (Evaluación Inicial)',
    atencion2: '2026-03-11 (Sesión Psicológica)',
    atencion3: '2026-03-18 (Sesión T.O. Rutinas)',
    atencion4: '2026-03-25 (Intervención Dupla)',
    atencion5: '',
    atencion6: '',
    atencion7: '',
    atencion8: '',
    atencion9: '',
    atencion10: '',
    totalAtenciones: 4,
    observacionAtenciones: 'Evolución favorable con regulación sensorial y apoyo emocional.',
  },
  {
    numero: 2,
    duplaACargo: 'Dupla 2 (Ps. Andrea Ríos - T.S. Marco Peña)',
    estado: 'Activo',
    fechaDerivacionDupla: '2026-03-08',
    fechaEgreso: '',
    fechaMaximaContactoInicial: '2026-03-11',
    fechaIngresoUego: '2026-03-07',
    observacionesIngreso: 'Derivación por equipo psicosocial comunitario.',
    nombre: 'Mateo Alejandro Castillo Rojas',
    rut: '24.112.334-K',
    edad: 8,
    eg: 'N/A',
    tipologia: 'Neurodesarrollo & Apoyo Familiar',
    diagnostico: 'Trastorno del Espectro Autista (TEA) Grado 1 + TDAH',
    observacionesDiagnostico: 'Dificultades en integración de pares y autorregulación.',
    ingresoHorarioEspecial: 'No',
    telefono: '+56 9 7654 3210',
    observacionesContacto: 'Contacto vía WhatsApp confirmado con el padre.',
    migrante: 'No',
    puebloOriginario: 'Mapuche',
    entregaRecuerdo: 'Sí',
    entregaDiptico: 'Sí',
    acompanamientoAtencionCerrada: 'No',
    controlAmbulatorioPsicosocial: 'Sí',
    atencion1: '2026-03-10 (Entrevista anamnesis)',
    atencion2: '2026-03-17 (Evaluación integral)',
    atencion3: '2026-03-24 (Plan de intervención)',
    atencion4: '',
    atencion5: '',
    atencion6: '',
    atencion7: '',
    atencion8: '',
    atencion9: '',
    atencion10: '',
    totalAtenciones: 3,
    observacionAtenciones: 'Se coordina reunión con colegio y adecuaciones curriculares.',
  },
  {
    numero: 3,
    duplaACargo: 'Dupla 1 (Ps. Tomás Valenzuela - T.O. Camila Soto)',
    estado: 'Egresado',
    fechaDerivacionDupla: '2026-01-10',
    fechaEgreso: '2026-03-20',
    fechaMaximaContactoInicial: '2026-01-13',
    fechaIngresoUego: '2026-01-09',
    observacionesIngreso: 'Ingreso programado por interconsulta de APS.',
    nombre: 'Sofía Antonia Morales Silva',
    rut: '21.987.654-1',
    edad: 16,
    eg: 'N/A',
    tipologia: 'Duelo & Manejo del Estrés',
    diagnostico: 'Reacción de adaptación y duelo complicado',
    observacionesDiagnostico: 'Cumplimiento satisfactorio de objetivos terapéuticos.',
    ingresoHorarioEspecial: 'No',
    telefono: '+56 9 9123 4567',
    observacionesContacto: 'Paciente y tutora con buena adherencia.',
    migrante: 'No',
    puebloOriginario: 'No',
    entregaRecuerdo: 'Sí',
    entregaDiptico: 'Sí',
    acompanamientoAtencionCerrada: 'No',
    controlAmbulatorioPsicosocial: 'Sí',
    atencion1: '2026-01-12',
    atencion2: '2026-01-19',
    atencion3: '2026-01-26',
    atencion4: '2026-02-09',
    atencion5: '2026-02-23',
    atencion6: '2026-03-09',
    atencion7: '2026-03-20 (Cierre y Egreso)',
    atencion8: '',
    atencion9: '',
    atencion10: '',
    totalAtenciones: 7,
    observacionAtenciones: 'Alta clínica consensuada con equipo interdisciplinario.',
  },
  {
    numero: 4,
    duplaACargo: 'Dupla 3 (Ps. Diego Morales - T.O. Carla Fuentes)',
    estado: 'En Espera',
    fechaDerivacionDupla: '2026-03-26',
    fechaEgreso: '',
    fechaMaximaContactoInicial: '2026-03-29',
    fechaIngresoUego: '2026-03-25',
    observacionesIngreso: 'Ingreso durante guardia de fin de semana.',
    nombre: 'Lucas Benjamín Navarrete Pérez',
    rut: '25.334.889-7',
    edad: 6,
    eg: 'N/A',
    tipologia: 'Conductual & Emocional',
    diagnostico: 'Desregulación emocional y conductual reactiva',
    observacionesDiagnostico: 'Pendiente primera evaluación presencial.',
    ingresoHorarioEspecial: 'UEGO',
    telefono: '+56 9 6543 2198',
    observacionesContacto: 'Llamar después de las 18:00 hrs.',
    migrante: 'Sí',
    puebloOriginario: 'No',
    entregaRecuerdo: 'No',
    entregaDiptico: 'Sí',
    acompanamientoAtencionCerrada: 'Sí',
    controlAmbulatorioPsicosocial: 'No',
    atencion1: '',
    atencion2: '',
    atencion3: '',
    atencion4: '',
    atencion5: '',
    atencion6: '',
    atencion7: '',
    atencion8: '',
    atencion9: '',
    atencion10: '',
    totalAtenciones: 0,
    observacionAtenciones: 'Programada primera citación telefónica para el día lunes.',
  },
  {
    numero: 5,
    duplaACargo: 'Dupla 2 (Ps. Andrea Ríos - T.S. Marco Peña)',
    estado: 'En Seguimiento',
    fechaDerivacionDupla: '2026-02-15',
    fechaEgreso: '',
    fechaMaximaContactoInicial: '2026-02-18',
    fechaIngresoUego: '2026-02-14',
    observacionesIngreso: 'Derivación prioritaria por situación de vulneración.',
    nombre: 'Catalina Ignacia Muñoz Vera',
    rut: '23.665.432-8',
    edad: 11,
    eg: 'N/A',
    tipologia: 'Protección Psicosocial',
    diagnostico: 'Trastorno de estrés postraumático agudo',
    observacionesDiagnostico: 'Requiere acompañamiento psicosocial intensivo.',
    ingresoHorarioEspecial: 'Horario Inhábil',
    telefono: '+56 9 4433 2211',
    observacionesContacto: 'Contacto con tía tutora legal acreditada.',
    migrante: 'No',
    puebloOriginario: 'Aymara',
    entregaRecuerdo: 'Sí',
    entregaDiptico: 'Sí',
    acompanamientoAtencionCerrada: 'Sí',
    controlAmbulatorioPsicosocial: 'Sí',
    atencion1: '2026-02-16 (Contención inicial)',
    atencion2: '2026-02-23 (Valoración social)',
    atencion3: '2026-03-02 (Sesión psicológica)',
    atencion4: '2026-03-12 (Coordinación red)',
    atencion5: '2026-03-22 (Sesión dupla)',
    atencion6: '',
    atencion7: '',
    atencion8: '',
    atencion9: '',
    atencion10: '',
    totalAtenciones: 5,
    observacionAtenciones: 'Buena alianza terapéutica, se observan avances en seguridad personal.',
  },
  {
    numero: 6,
    duplaACargo: 'Dupla 1 (Ps. Tomás Valenzuela - T.O. Camila Soto)',
    estado: 'Activo',
    fechaDerivacionDupla: '2026-03-15',
    fechaEgreso: '',
    fechaMaximaContactoInicial: '2026-03-18',
    fechaIngresoUego: '2026-03-14',
    observacionesIngreso: 'Ingreso preventivo por dificultades en adaptación escolar.',
    nombre: 'Joaquín Emilio Silva Tapia',
    rut: '23.889.102-5',
    edad: 13,
    eg: 'N/A',
    tipologia: 'Integración Sensorial & Adaptación',
    diagnostico: 'Disfunción de Integración Sensorial y Fobia Escolar',
    observacionesDiagnostico: 'Hipersensibilidad auditiva y táctil en contexto de aula.',
    ingresoHorarioEspecial: 'No',
    telefono: '+56 9 5566 7788',
    observacionesContacto: 'Padres solicitan atención en jornada matutina.',
    migrante: 'No',
    puebloOriginario: 'No',
    entregaRecuerdo: 'Sí',
    entregaDiptico: 'Sí',
    acompanamientoAtencionCerrada: 'No',
    controlAmbulatorioPsicosocial: 'Sí',
    atencion1: '2026-03-17 (Perfil sensorial)',
    atencion2: '2026-03-24 (Estrategias sensoriales)',
    atencion3: '',
    atencion4: '',
    atencion5: '',
    atencion6: '',
    atencion7: '',
    atencion8: '',
    atencion9: '',
    atencion10: '',
    totalAtenciones: 2,
    observacionAtenciones: 'Se elabora pauta de descanso sensorial para la jornada de clases.',
  },
];
